### PR TITLE
fix/upgrade-to-opentelemetry-0.6

### PR DESCRIPTION
**Pull request by ghost**
Hi Marc, 
Here's a PR to upgrade to opentelemetry 0.6
Best, 
Bryan

### CODE REVIEW

**Comment by ghost** [comment]
@garthk @marcdel @luizmiranda7 any interest ?

**Review by luizmiranda7 — APPROVED** [review]

**Comment by ghost** [comment]
Ty. @luizmiranda7 . Still need a merge from one of @garthk / @marcdel

**Comment by garthk** [comment]
It'll be @marcdel, no? I'm not a maintainer on this project, sorry.

**Comment by ghost** [comment]
@marcdel - any interest? Happy to help with maintenance (on behalf of [ESL](https://github.com/esl) if you're interested.

**Pull request merged**
