### PR TITLE
Extend included vars

### PR DESCRIPTION
**Pull request by leggebroten**
## Issues
1) OTLP attribute values can only accept strings, integers, doubles/floats, or boolean.

https://hexdocs.pm/opentelemetry_api/OpenTelemetry.html#t:attributes_map/0

Currently if the target of the `:include` is not one of these primitives, the attribute will not be added to the span.

2) `:include` cannot handle string-key maps as a `bound variable`

## Solutions provided
1) do an `inspect` if attribute value is not one of the allowed primitives. 
2) Handle indexing into string-keyed map

### CODE REVIEW

**Comment by marcdel** [comment]
Thanks so much for this! Gimme a bit to wrap my head around it, but it looks good!

**Comment by fendent** [comment]
Just started using this and just came here to see if someone had done something like this. Looking forward to seeing this merged!

**Comment by marcdel** [comment]
@fendent yooo! curious which part: the `inspect` on non-otel approved types, or indexing into string keyed maps?

**Comment by fendent** [comment]
> @fendent yooo! curious which part: the `inspect` on non-otel approved types, or indexing into string keyed maps?

Both actually! I made a quick proto of the string keyed map but haven't had time to flesh it out.

**Comment by marcdel** [comment]
Dope! There are a couple edge cases I want to make sure get covered* before I publish a new version but I'm good to merge this.

\* totally could have been an issue with the existing implementation but I just found them poking around with this changeset

**Comment by leggebroten** [comment]
You're welcome.
Was a fun project

**Pull request merged**
